# Generated by Django 3.1.5 on 2021-01-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Post',
        ),
    ]
